// frontend/src/components/base/Card.vue
<script setup>
defineProps({
  title: { type: String, default: '' },
  subtitle: { type: String, default: '' },
  padding: { type: String, default: '1.5rem' },
  hoverable: { type: Boolean, default: false },
  actions: { type: Boolean, default: false },
  style: { type: Object, default: () => ({}) }
})

const emit = defineEmits(['click'])
</script>

<template>
  <div
    class="metric-card"
    :class="{ 'card-hoverable': hoverable }"
    :style="{
      padding: padding || '1.5rem',
      cursor: hoverable ? 'pointer' : undefined,
      border: '1px solid var(--border-color)',
      borderRadius: 'var(--radius-lg)',
      background: 'var(--bg-card)',
      transition: 'all 0.2s ease',
      ...style
    }"
    @click="hoverable && emit('click')"
  >
    <div
      v-if="title || subtitle || $slots.actions"
      style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1rem; gap: 1rem;"
    >
      <div style="display: flex; flex-direction: column; gap: 0.15rem;">
        <h3
          v-if="title"
          style="font-size: 0.95rem; font-weight: 700; color: var(--text-primary); margin: 0;"
        >
          {{ title }}
        </h3>
        <p
          v-if="subtitle"
          style="font-size: 0.8rem; color: var(--text-secondary); margin: 0;"
        >
          {{ subtitle }}
        </p>
      </div>
      <div
        v-if="$slots.actions"
        style="display: flex; gap: 0.5rem; flex-shrink: 0;"
      >
        <slot name="actions" />
      </div>
    </div>
    <slot />
  </div>
</template>

// frontend/src/components/ui/Card.tsx
import React from 'react';

interface CardProps {
  children: React.ReactNode;
  className?: string;
  padding?: string;
  hoverable?: boolean;
  onClick?: () => void;
  title?: string;
  subtitle?: string;
  actions?: React.ReactNode;
  style?: React.CSSProperties;
}

export const Card: React.FC<CardProps> = ({
  children,
  className = '',
  padding,
  hoverable = false,
  onClick,
  title,
  subtitle,
  actions,
  style,
}) => {
  const Component = onClick ? 'button' : 'div';

  return (
    <Component
      className={`metric-card card-hover ${hoverable ? 'card-hoverable' : ''} ${className}`}
      onClick={onClick}
      style={{
        padding: padding || '1.5rem',
        cursor: onClick ? 'pointer' : undefined,
        textAlign: onClick ? 'left' : undefined,
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--radius-lg)',
        background: 'var(--bg-card)',
        transition: 'all 0.2s ease',
        ...style,
      }}
    >
      {(title || subtitle || actions) && (
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          marginBottom: children ? '1rem' : 0,
          gap: '1rem',
        }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.15rem' }}>
            {title && (
              <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
                {title}
              </h3>
            )}
            {subtitle && (
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', margin: 0 }}>
                {subtitle}
              </p>
            )}
          </div>
          {actions && <div style={{ display: 'flex', gap: '0.5rem', flexShrink: 0 }}>{actions}</div>}
        </div>
      )}
      {children}
    </Component>
  );
};
